{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "42b46b06-577c-4c39-9268-33afb4ff098e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: seaborn in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from seaborn) (2.4.6)\n",
      "Requirement already satisfied: pandas>=1.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from seaborn) (3.0.6)\n",
      "Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from seaborn) (3.11.2)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)\n",
      "Requirement already satisfied: cycler>=0.10 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.28.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.66.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)\n",
      "Requirement already satisfied: packaging>=20.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)\n",
      "Requirement already satisfied: pillow>=9 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)\n",
      "Requirement already satisfied: pyparsing>=3 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)\n",
      "Requirement already satisfied: tzdata in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from pandas>=1.2->seaborn) (2026.4)\n",
      "Requirement already satisfied: six>=1.5 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)\n",
      "Requirement already satisfied: requests in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (2.34.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from requests) (3.5.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from requests) (3.20)\n",
      "Requirement already satisfied: urllib3<3,>=1.26 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from requests) (2.8.0)\n",
      "Requirement already satisfied: certifi>=2023.5.7 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from requests) (2026.7.22)\n",
      "Requirement already satisfied: numpy in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (2.4.6)\n",
      "Requirement already satisfied: pandas in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (3.0.6)\n",
      "Requirement already satisfied: scikit-learn in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (1.9.1)\n",
      "Requirement already satisfied: matplotlib in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (3.11.2)\n",
      "Requirement already satisfied: jupyter in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (1.1.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: tzdata in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from pandas) (2026.4)\n",
      "Requirement already satisfied: scipy>=1.10.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from scikit-learn) (1.17.1)\n",
      "Requirement already satisfied: joblib>=1.4.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from scikit-learn) (1.6.0)\n",
      "Requirement already satisfied: narwhals>=2.0.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from scikit-learn) (2.26.0)\n",
      "Requirement already satisfied: threadpoolctl>=3.5.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from scikit-learn) (3.7.0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib) (1.3.3)\n",
      "Requirement already satisfied: cycler>=0.10 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.28.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib) (4.66.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib) (1.5.1)\n",
      "Requirement already satisfied: packaging>=20.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib) (26.3)\n",
      "Requirement already satisfied: pillow>=9 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib) (12.3.0)\n",
      "Requirement already satisfied: pyparsing>=3 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from matplotlib) (3.3.3)\n",
      "Requirement already satisfied: notebook in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter) (7.6.3)\n",
      "Requirement already satisfied: jupyter-console in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter) (6.6.3)\n",
      "Requirement already satisfied: nbconvert in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter) (7.17.1)\n",
      "Requirement already satisfied: ipykernel in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter) (7.3.0)\n",
      "Requirement already satisfied: ipywidgets in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter) (8.1.9)\n",
      "Requirement already satisfied: jupyterlab in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter) (4.6.4)\n",
      "Requirement already satisfied: cloudpickle>=3.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)\n",
      "Requirement already satisfied: six>=1.5 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: comm>=0.1.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (0.2.3)\n",
      "Requirement already satisfied: debugpy>=1.6.5 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (1.8.22)\n",
      "Requirement already satisfied: ipython>=7.23.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (9.17.1)\n",
      "Requirement already satisfied: jupyter-client>=8.9.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (8.10.0)\n",
      "Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (5.9.1)\n",
      "Requirement already satisfied: matplotlib-inline>=0.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (0.2.2)\n",
      "Requirement already satisfied: nest-asyncio2>=1.7.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (1.7.3)\n",
      "Requirement already satisfied: psutil>=5.7 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (7.2.2)\n",
      "Requirement already satisfied: pyzmq>=25 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (27.2.0)\n",
      "Requirement already satisfied: tornado>=6.4.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (6.5.10)\n",
      "Requirement already satisfied: traitlets>=5.4.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipykernel->jupyter) (5.16.1)\n",
      "Requirement already satisfied: colorama>=0.4.4 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)\n",
      "Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)\n",
      "Requirement already satisfied: jedi>=0.18.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.20.0)\n",
      "Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.53)\n",
      "Requirement already satisfied: pygments>=2.14.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.21.0)\n",
      "Requirement already satisfied: stack_data>=0.6.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)\n",
      "Requirement already satisfied: typing_extensions>=4.6 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.16.0)\n",
      "Requirement already satisfied: wcwidth>=0.1.4 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.9.1)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->jupyter) (0.8.7)\n",
      "Requirement already satisfied: platformdirs>=2.5 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.12.1)\n",
      "Requirement already satisfied: executing>=1.2.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)\n",
      "Requirement already satisfied: asttokens>=2.1.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.2)\n",
      "Requirement already satisfied: pure-eval in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.4)\n",
      "Requirement already satisfied: widgetsnbextension~=4.0.16 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipywidgets->jupyter) (4.0.16)\n",
      "Requirement already satisfied: jupyterlab_widgets~=3.0.17 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from ipywidgets->jupyter) (3.0.17)\n",
      "Requirement already satisfied: async-lru>=1.0.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (2.3.0)\n",
      "Requirement already satisfied: httpx<1,>=0.25.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (0.28.1)\n",
      "Requirement already satisfied: jinja2>=3.0.3 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (3.1.6)\n",
      "Requirement already satisfied: jupyter-builder>=1.0.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (1.2.3)\n",
      "Requirement already satisfied: jupyter-lsp>=2.0.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (2.3.1)\n",
      "Requirement already satisfied: jupyter-server<3,>=2.19.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (2.21.1)\n",
      "Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (2.28.1)\n",
      "Requirement already satisfied: notebook-shim>=0.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab->jupyter) (0.2.4)\n",
      "Requirement already satisfied: anyio in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.15.1)\n",
      "Requirement already satisfied: certifi in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.7.22)\n",
      "Requirement already satisfied: httpcore==1.* in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)\n",
      "Requirement already satisfied: idna in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.20)\n",
      "Requirement already satisfied: h11>=0.16 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)\n",
      "Requirement already satisfied: argon2-cffi>=21.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.1.0)\n",
      "Requirement already satisfied: jupyter-events>=0.11.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.12.1)\n",
      "Requirement already satisfied: jupyter-server-terminals>=0.4.4 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.5.4)\n",
      "Requirement already satisfied: nbformat>=5.3.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (5.11.1)\n",
      "Requirement already satisfied: overrides>=5.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (7.7.0)\n",
      "Requirement already satisfied: prometheus-client>=0.9 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.26.0)\n",
      "Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0.5)\n",
      "Requirement already satisfied: send2trash>=1.8.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.1.0)\n",
      "Requirement already satisfied: terminado>=0.8.3 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.18.1)\n",
      "Requirement already satisfied: websocket-client>=1.7 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.9.2)\n",
      "Requirement already satisfied: babel>=2.10 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)\n",
      "Requirement already satisfied: json5>=0.9.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.15.0)\n",
      "Requirement already satisfied: jsonschema>=4.18.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)\n",
      "Requirement already satisfied: requests>=2.31 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.34.2)\n",
      "Requirement already satisfied: argon2-cffi-bindings in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (26.1.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.25.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2026.6.3)\n",
      "Requirement already satisfied: python-json-logger>=2.0.4 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (4.2.0)\n",
      "Requirement already satisfied: pyyaml>=5.3 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)\n",
      "Requirement already satisfied: rfc3339-validator in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.4)\n",
      "Requirement already satisfied: rfc3986-validator>=0.1.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.1)\n",
      "Requirement already satisfied: fqdn in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.6.0)\n",
      "Requirement already satisfied: isoduration in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (20.11.0)\n",
      "Requirement already satisfied: jsonpointer>1.13 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.1.1)\n",
      "Requirement already satisfied: rfc3987-syntax>=1.1.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.1.0)\n",
      "Requirement already satisfied: uri-template in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.0)\n",
      "Requirement already satisfied: webcolors>=24.6.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.10.0)\n",
      "Requirement already satisfied: beautifulsoup4 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nbconvert->jupyter) (4.15.0)\n",
      "Requirement already satisfied: bleach!=5.0.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.4.0)\n",
      "Requirement already satisfied: defusedxml in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nbconvert->jupyter) (0.7.1)\n",
      "Requirement already satisfied: jupyterlab-pygments in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nbconvert->jupyter) (0.3.0)\n",
      "Requirement already satisfied: mistune<4,>=2.0.3 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nbconvert->jupyter) (3.3.4)\n",
      "Requirement already satisfied: nbclient>=0.5.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nbconvert->jupyter) (0.11.0)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nbconvert->jupyter) (1.5.1)\n",
      "Requirement already satisfied: webencodings in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.6.1)\n",
      "Requirement already satisfied: tinycss2>=1.1.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.5.1)\n",
      "Requirement already satisfied: fastjsonschema>=2.15 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.22.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.5.1)\n",
      "Requirement already satisfied: urllib3<3,>=1.26 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.8.0)\n",
      "Requirement already satisfied: lark>=1.2.2 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.1)\n",
      "Requirement already satisfied: cffi>=1.0.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.1.1)\n",
      "Requirement already satisfied: pycparser in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0)\n",
      "Requirement already satisfied: soupsieve>=1.6.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.10)\n",
      "Requirement already satisfied: arrow>=0.15.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.4.0)\n",
      "Requirement already satisfied: nltk in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (3.10.3)\n",
      "Requirement already satisfied: defusedxml in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nltk) (0.7.1)\n",
      "Requirement already satisfied: click in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nltk) (8.5.0)\n",
      "Requirement already satisfied: joblib in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nltk) (1.6.0)\n",
      "Requirement already satisfied: regex>=2021.8.3 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nltk) (2026.9.10)\n",
      "Requirement already satisfied: tqdm in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from nltk) (4.70.1)\n",
      "Requirement already satisfied: cloudpickle>=3.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from joblib->nltk) (3.1.2)\n",
      "Requirement already satisfied: colorama in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from tqdm->nltk) (0.4.6)\n"
     ]
    }
   ],
   "source": [
    "!pip install seaborn\n",
    "!pip install requests\n",
    "!pip install numpy pandas scikit-learn matplotlib jupyter\n",
    "!pip install nltk\n",
    "import pandas as pd\n",
    "import re\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "47bafd56-aa2b-411f-9720-61b2b9f1a44d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(\n",
    "    r\"C:\\Users\\Xaverine\\Downloads\\spam.csv\",\n",
    "    encoding=\"latin-1\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "cb3f308d-8406-4fef-8fc2-13f9749a76cf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Rows: 5572\n",
      "label\n",
      "ham     4825\n",
      "spam     747\n",
      "Name: count, dtype: int64\n",
      "  label                                            message\n",
      "0   ham  Go until jurong point, crazy.. Available only ...\n",
      "1   ham                      Ok lar... Joking wif u oni...\n",
      "2  spam  Free entry in 2 a wkly comp to win FA Cup fina...\n",
      "3   ham  U dun say so early hor... U c already then say...\n",
      "4   ham  Nah I don't think he goes to usf, he lives aro...\n"
     ]
    }
   ],
   "source": [
    "df = df.iloc[:, :2]                                 # drop junk columns\n",
    "df.columns = [\"label\", \"message\"]\n",
    "\n",
    "print(f\"Rows: {len(df)}\")\n",
    "print(df[\"label\"].value_counts())\n",
    "print(df.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8845a581-1b94-46e2-b2fa-5a119b2e69ea",
   "metadata": {},
   "source": [
    "Class balance (ham dominates → watch false positives)\n",
    "\n",
    "Duplicates (SMS forwarding creates many)\n",
    "\n",
    "Missing values\n",
    "\n",
    "Message length distribution (spam is usually longer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "0050e122-872d-4b06-957c-69ba47c51cb0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "After cleaning: 5169 messages\n",
      "Spam %: 12.63%\n"
     ]
    }
   ],
   "source": [
    "df.dropna(subset=[\"label\", \"message\"], inplace=True)\n",
    "df.drop_duplicates(subset=[\"message\"], inplace=True)\n",
    "df[\"label_num\"] = df[\"label\"].map({\"ham\": 0, \"spam\": 1})\n",
    "\n",
    "print(f\"After cleaning: {len(df)} messages\")\n",
    "print(f\"Spam %: {df['label_num'].mean()*100:.2f}%\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eb292dc9-f2e4-4a1e-9baf-4d456423d00e",
   "metadata": {},
   "source": [
    "Clean the Text (NLP Preprocessing)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "b03e4fd9-90d1-486d-b47c-8c0fcf3c2ede",
   "metadata": {},
   "outputs": [],
   "source": [
    "import re, string\n",
    "import nltk\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.stem import PorterStemmer\n",
    "\n",
    "nltk.download(\"stopwords\", quiet=True)\n",
    "stop_words = set(stopwords.words(\"english\"))\n",
    "stemmer = PorterStemmer()\n",
    "\n",
    "def clean_text(text):\n",
    "    # 1. Lowercase\n",
    "    text = text.lower()\n",
    "\n",
    "    # 2. Remove URLs\n",
    "    text = re.sub(r\"http\\S+|www\\.\\S+\", \"\", text)\n",
    "\n",
    "    # 3. Remove email addresses\n",
    "    text = re.sub(r\"\\S+@\\S+\", \"\", text)\n",
    "\n",
    "    # 4. Remove long digit runs (phone numbers, prize amounts)\n",
    "    text = re.sub(r\"\\b\\d{5,}\\b\", \"\", text)\n",
    "\n",
    "    # 5. Remove punctuation and remaining digits\n",
    "    text = text.translate(str.maketrans(\"\", \"\", string.punctuation))\n",
    "    text = re.sub(r\"\\d+\", \"\", text)\n",
    "\n",
    "    # 6. Tokenize (split on whitespace — fine after cleaning)\n",
    "    tokens = text.split()\n",
    "\n",
    "    # 7. Remove stopwords & short tokens\n",
    "    tokens = [t for t in tokens if t not in stop_words and len(t) > 1]\n",
    "\n",
    "    # 8. Stem (running → run, claimed → claim)\n",
    "    tokens = [stemmer.stem(t) for t in tokens]\n",
    "\n",
    "    return \" \".join(tokens)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "e8757768-afb7-443b-bb11-293e262ac39d",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing installation: scikit-learn 1.9.1\n",
      "Uninstalling scikit-learn-1.9.1:\n",
      "  Successfully uninstalled scikit-learn-1.9.1\n",
      "Found existing installation: scipy 1.17.1\n",
      "Uninstalling scipy-1.17.1:\n",
      "  Successfully uninstalled scipy-1.17.1\n",
      "Found existing installation: numpy 2.4.6\n",
      "Uninstalling numpy-2.4.6:\n",
      "  Successfully uninstalled numpy-2.4.6\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Failed to remove contents in a temporary directory 'C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages\\~-learn'.\n",
      "You can safely remove it manually.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (26.2.1)\n",
      "Collecting numpy\n",
      "  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)\n",
      "Collecting scipy\n",
      "  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)\n",
      "Collecting scikit-learn\n",
      "  Using cached scikit_learn-1.9.1-cp311-cp311-win_amd64.whl.metadata (9.3 kB)\n",
      "Requirement already satisfied: joblib>=1.4.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from scikit-learn) (1.6.0)\n",
      "Requirement already satisfied: narwhals>=2.0.1 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from scikit-learn) (2.26.0)\n",
      "Requirement already satisfied: threadpoolctl>=3.5.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from scikit-learn) (3.7.0)\n",
      "Requirement already satisfied: cloudpickle>=3.0 in C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)\n",
      "Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)\n",
      "Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)\n",
      "Using cached scikit_learn-1.9.1-cp311-cp311-win_amd64.whl (8.3 MB)\n",
      "Installing collected packages: numpy, scipy, scikit-learn\n",
      "\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ---------------------------------------- 0/3 [numpy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   ------------- -------------------------- 1/3 [scipy]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   -------------------------- ------------- 2/3 [scikit-learn]\n",
      "   ---------------------------------------- 3/3 [scikit-learn]\n",
      "\n",
      "Successfully installed numpy-2.4.6 scikit-learn-1.9.1 scipy-1.17.1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n"
     ]
    }
   ],
   "source": [
    "!pip uninstall -y scikit-learn scipy numpy\n",
    "!pip install --upgrade pip\n",
    "!pip install numpy scipy scikit-learn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "0c342d99-eda9-4f08-96d2-da154c1bb82d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['label', 'message', 'label_num']\n"
     ]
    }
   ],
   "source": [
    "print(df.columns.tolist())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "07931cd2-6cbf-459f-9c5b-f7f76370e2df",
   "metadata": {},
   "outputs": [],
   "source": [
    "#split data\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X = df[\"message\"]\n",
    "y = df[\"label_num\"]\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y,\n",
    "    test_size=0.2,          # 80/20 split\n",
    "    random_state=42,        # reproducibility\n",
    "    stratify=y,             # preserve spam/ham ratio in both sets\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "f1cc614d-adda-42c0-8012-1d2e7c6f0c08",
   "metadata": {},
   "outputs": [],
   "source": [
    "#TF-IDF converts each message into a numeric vector\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "\n",
    "tfidf = TfidfVectorizer(\n",
    "    max_features=5000,       # keep top 5000 terms\n",
    "    ngram_range=(1, 2),      # unigrams + bigrams (\"call now\")\n",
    "    min_df=2,                # ignore terms appearing in <2 docs\n",
    "    max_df=0.95,             # ignore terms in >95% of docs\n",
    ")\n",
    "\n",
    "X_train_vec = tfidf.fit_transform(X_train)\n",
    "X_test_vec  = tfidf.transform(X_test)     # ⚠️ transform, not fit_transform!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "193bb222-3835-4f7e-af8b-60e8d8e01083",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trained: Naive Bayes\n",
      "Trained: Logistic Regression\n",
      "Trained: Linear SVM\n"
     ]
    }
   ],
   "source": [
    "#Train Multiple Models\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import LinearSVC\n",
    "#from sklearn.ensemble import RandomForestClassifier\n",
    "\n",
    "models = {\n",
    "    \"Naive Bayes\":         MultinomialNB(),\n",
    "    \"Logistic Regression\": LogisticRegression(max_iter=1000),\n",
    "    \"Linear SVM\":          LinearSVC(),\n",
    "    #\"Random Forest\":       RandomForestClassifier(n_estimators=200, n_jobs=-1),\n",
    "}\n",
    "\n",
    "trained = {}\n",
    "for name, model in models.items():\n",
    "    model.fit(X_train_vec, y_train)\n",
    "    trained[name] = model\n",
    "    print(f\"Trained: {name}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "3397149b-c3f1-41d8-8b1e-a08eb7d07f30",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              Model  Accuracy  Precision   Recall       F1\n",
      "         Linear SVM  0.981625   0.982759 0.870229 0.923077\n",
      "Logistic Regression  0.967118   0.989899 0.748092 0.852174\n",
      "        Naive Bayes  0.966151   1.000000 0.732824 0.845815\n"
     ]
    }
   ],
   "source": [
    "#Evaluate & Compare\n",
    "\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, precision_score,\n",
    "    recall_score, f1_score, confusion_matrix,\n",
    ")\n",
    "results = []\n",
    "for name, model in trained.items():\n",
    "    preds = model.predict(X_test_vec)\n",
    "    results.append({\n",
    "        \"Model\": name,\n",
    "        \"Accuracy\":  accuracy_score(y_test, preds),\n",
    "        \"Precision\": precision_score(y_test, preds),\n",
    "        \"Recall\":    recall_score(y_test, preds),\n",
    "        \"F1\":        f1_score(y_test, preds),\n",
    "    })\n",
    "\n",
    "import pandas as pd\n",
    "results_df = pd.DataFrame(results).sort_values(\"F1\", ascending=False)\n",
    "print(results_df.to_string(index=False))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "85022334-c28c-40dc-8f26-285f581e6c58",
   "metadata": {},
   "outputs": [],
   "source": [
    "#save the best model\n",
    "import pickle\n",
    "\n",
    "best_model = trained[\"Linear SVM\"]\n",
    "\n",
    "with open(\"model.pkl\", \"wb\") as f:\n",
    "    pickle.dump(best_model, f)\n",
    "\n",
    "with open(\"vectorizer.pkl\", \"wb\") as f:\n",
    "    pickle.dump(tfidf, f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e25e6057-2bb9-40bd-a9e7-eefb339b4e95",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-09-29 06:17:41.075 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.498 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Xaverine\\AppData\\Local\\Python\\pythoncore-3.11-64\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-09-29 06:17:41.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.505 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.507 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.507 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.515 Session state does not function when running a script without `streamlit run`\n",
      "2026-09-29 06:17:41.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.519 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-09-29 06:17:41.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# Streamlit interface\n",
    "st.title(\"📱 SMS Spam Detection\")\n",
    "st.write(\"Enter an SMS message to determine whether it is Spam or Ham.\")\n",
    "\n",
    "message = st.text_area(\n",
    "    \"Enter your SMS message:\",\n",
    "    placeholder=\"Example: Congratulations! You have won a free prize...\"\n",
    ")\n",
    "\n",
    "if st.button(\"Predict\"):\n",
    "    if message.strip() == \"\":\n",
    "        st.warning(\"Please enter an SMS message.\")\n",
    "    else:\n",
    "        # Clean message\n",
    "        cleaned_message = clean_text(message)\n",
    "\n",
    "        # Convert text to TF-IDF\n",
    "        message_vector = vectorizer.transform([cleaned_message])\n",
    "\n",
    "        # Prediction\n",
    "        prediction = model.predict(message_vector)[0]\n",
    "\n",
    "        if prediction == 1:\n",
    "            st.error(\"🚨 SPAM MESSAGE\")\n",
    "        else:\n",
    "            st.success(\"✅ HAM MESSAGE\")\n",
    "\n",
    "        st.write(\"Original message:\")\n",
    "        st.write(message)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c3e8c1c-d9b8-4053-ab85-49d9892a6417",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
